/* QUESTION: Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.

Answer: 1533776805 (5.4s)
*/

let triangularNumbers = [];
let pentagonalNumbers = [];
let hexagonalNumbers = [];

for (let i = 1; i < 100000; i++) {
    triangularNumbers.push(0.5 * i * (i + 1));
    pentagonalNumbers.push(0.5 * i * (3 * i - 1));
    hexagonalNumbers.push(i * (2 * i - 1));
}

for (let num of triangularNumbers) {
    if (pentagonalNumbers.includes(num) && hexagonalNumbers.includes(num) && num != 1 && num != 40755) {
        console.log(num);
        break;
    }
}